using Infrastructure;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container
builder.Services.AddOpenApi();
builder.Services.AddEndpointsApiExplorer();

// Add controllers
builder.Services.AddControllers();

// Add Authentication (JWT Bearer)
builder.Services.AddAuthentication("Bearer")
    .AddJwtBearer("Bearer", options =>
    {
        options.Authority = builder.Configuration["Auth:Authority"] ?? "https://localhost:5001";
        options.Audience = builder.Configuration["Auth:Audience"] ?? "klippr-api";
        options.RequireHttpsMetadata = builder.Environment.IsProduction();
    });

// Add Authorization
builder.Services.AddAuthorization();

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddPolicy("AllowAll", policy =>
    {
        policy.AllowAnyOrigin()
            .AllowAnyMethod()
            .AllowAnyHeader();
    });
});

// Register Profile module services
var profileConnectionString = builder.Configuration.GetConnectionString("DefaultConnection") 
    ?? "Data Source=klippr.db";
builder.Services.AddProfileServices(profileConnectionString, builder.Configuration);

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.MapOpenApi();
    app.UseSwaggerUI(options =>
    {
        // Ensure Swagger UI points to the JSON generated by MapOpenApi()
        options.SwaggerEndpoint("/openapi/v1.json", "Klippr API v1");
        options.RoutePrefix = "swagger";
    });
}

app.UseHttpsRedirection();
app.UseCors("AllowAll");
app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();

app.Run();