// <auto-generated />
using System;
using Klippr_Backend.Profile.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klippr_Backend.Profile.Infrastructure.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20260605233336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Klippr_Backend.Profile.Domain.Aggregates.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("BusinessName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("TaxId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.Property<DateTime?>("VerificationApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("VerificationApprovedAt");

                    b.Property<string>("VerificationDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("VerificationDocumentUrl");

                    b.Property<DateTime?>("VerificationSubmittedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("VerificationSubmittedAt");

                    b.HasKey("Id");

                    b.ToTable("BusinessProfiles", (string)null);
                });

            modelBuilder.Entity("Klippr_Backend.Profile.Domain.Aggregates.ConsumerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("IsActive");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("PhoneNumber");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("UpdatedAt");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.ToTable("ConsumerProfiles", (string)null);
                });

            modelBuilder.Entity("Klippr_Backend.Profile.Domain.Aggregates.BusinessProfile", b =>
                {
                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("BusinessProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocationCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocationCountry");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("LocationLatitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("LocationLongitude");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocationState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("LocationStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("LocationZipCode");

                            b1.HasKey("BusinessProfileId");

                            b1.ToTable("BusinessProfiles");

                            b1.WithOwner()
                                .HasForeignKey("BusinessProfileId");
                        });

                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("BusinessProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<double>("AverageRating")
                                .HasColumnType("double")
                                .HasColumnName("RatingAverage");

                            b1.Property<int>("FiveStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingFiveStarCount");

                            b1.Property<int>("FourStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingFourStarCount");

                            b1.Property<int>("OneStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingOneStarCount");

                            b1.Property<int>("ThreeStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingThreeStarCount");

                            b1.Property<int>("TotalReviews")
                                .HasColumnType("int")
                                .HasColumnName("RatingTotalReviews");

                            b1.Property<int>("TwoStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingTwoStarCount");

                            b1.HasKey("BusinessProfileId");

                            b1.ToTable("BusinessProfiles");

                            b1.WithOwner()
                                .HasForeignKey("BusinessProfileId");
                        });

                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.BusinessCategory", "Category", b1 =>
                        {
                            b1.Property<Guid>("BusinessProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("CategoryValue");

                            b1.HasKey("BusinessProfileId");

                            b1.ToTable("BusinessProfiles");

                            b1.WithOwner()
                                .HasForeignKey("BusinessProfileId");
                        });

                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.VerificationStatus", "VerificationStatus", b1 =>
                        {
                            b1.Property<Guid>("BusinessProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("VerificationStatus");

                            b1.HasKey("BusinessProfileId");

                            b1.ToTable("BusinessProfiles");

                            b1.WithOwner()
                                .HasForeignKey("BusinessProfileId");
                        });

                    b.Navigation("Category")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Rating");

                    b.Navigation("VerificationStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("Klippr_Backend.Profile.Domain.Aggregates.ConsumerProfile", b =>
                {
                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("ConsumerProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocationCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocationCountry");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double")
                                .HasColumnName("LocationLatitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double")
                                .HasColumnName("LocationLongitude");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("LocationState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("varchar(200)")
                                .HasColumnName("LocationStreet");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varchar(20)")
                                .HasColumnName("LocationZipCode");

                            b1.HasKey("ConsumerProfileId");

                            b1.ToTable("ConsumerProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ConsumerProfileId");
                        });

                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.Rating", "Rating", b1 =>
                        {
                            b1.Property<Guid>("ConsumerProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<double>("AverageRating")
                                .HasColumnType("double")
                                .HasColumnName("RatingAverage");

                            b1.Property<int>("FiveStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingFiveStarCount");

                            b1.Property<int>("FourStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingFourStarCount");

                            b1.Property<int>("OneStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingOneStarCount");

                            b1.Property<int>("ThreeStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingThreeStarCount");

                            b1.Property<int>("TotalReviews")
                                .HasColumnType("int")
                                .HasColumnName("RatingTotalReviews");

                            b1.Property<int>("TwoStarCount")
                                .HasColumnType("int")
                                .HasColumnName("RatingTwoStarCount");

                            b1.HasKey("ConsumerProfileId");

                            b1.ToTable("ConsumerProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ConsumerProfileId");
                        });

                    b.OwnsOne("Klippr_Backend.Profile.Domain.ValueObjects.SavingsStatistics", "SavingsStatistics", b1 =>
                        {
                            b1.Property<Guid>("ConsumerProfileId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("LastUpdated")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("SavingsLastUpdated");

                            b1.Property<int>("PromotionsSaved")
                                .HasColumnType("int")
                                .HasColumnName("SavingsPromotionsSaved");

                            b1.Property<int>("PromotionsUsed")
                                .HasColumnType("int")
                                .HasColumnName("SavingsPromotionsUsed");

                            b1.Property<decimal>("TotalSavings")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("SavingsTotalSavings");

                            b1.HasKey("ConsumerProfileId");

                            b1.ToTable("ConsumerProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ConsumerProfileId");
                        });

                    b.Navigation("Location");

                    b.Navigation("Rating");

                    b.Navigation("SavingsStatistics");
                });
#pragma warning restore 612, 618
        }
    }
}
