// <auto-generated />
using System;
using Klippr_Backend.Promotions.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klippr_Backend.Promotions.Infrastructure.Migrations
{
    [DbContext(typeof(PromotionDbContext))]
    partial class PromotionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Klippr_Backend.Promotions.Domain.Aggregates.Promotion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("RedemptionCap")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.HasIndex("Status");

                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("Klippr_Backend.Promotions.Domain.Aggregates.Promotion", b =>
                {
                    b.OwnsOne("Klippr_Backend.Promotions.Domain.ValueObjects.DiscountValue", "Discount", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("char(36)");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("DiscountAmount");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("varchar(32)")
                                .HasColumnName("DiscountType");

                            b1.HasKey("PromotionId");

                            b1.ToTable("Promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.OwnsOne("Klippr_Backend.Promotions.Domain.ValueObjects.TimeFrame", "ValidityPeriod", b1 =>
                        {
                            b1.Property<Guid>("PromotionId")
                                .HasColumnType("char(36)");

                            b1.Property<DateTime>("EndDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("EndDate");

                            b1.Property<DateTime>("StartDate")
                                .HasColumnType("datetime(6)")
                                .HasColumnName("StartDate");

                            b1.HasKey("PromotionId");

                            b1.HasIndex("StartDate", "EndDate");

                            b1.ToTable("Promotions");

                            b1.WithOwner()
                                .HasForeignKey("PromotionId");
                        });

                    b.Navigation("Discount")
                        .IsRequired();

                    b.Navigation("ValidityPeriod")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
