// <auto-generated />
using System;
using Klippr_Backend.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Klippr_Backend.shared.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260709014528_WidenPreferencesUserIdColumn")]
    partial class WidenPreferencesUserIdColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Klippr_Backend.Favorites.Domain.Aggregates.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("FavoriteId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("favorite_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_archived");

                    b.Property<string>("PromotionId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("promotion_id");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_favorites");

                    b.HasIndex("FavoriteId")
                        .IsUnique()
                        .HasDatabaseName("i_x_favorites_favorite_id");

                    b.HasIndex("UserId", "PromotionId")
                        .IsUnique()
                        .HasDatabaseName("i_x_favorites_user_id_promotion_id");

                    b.ToTable("favorites");
                });

            modelBuilder.Entity("Klippr_Backend.Setting.Domain.Model.Aggregate.Preference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("dark_mode");

                    b.Property<bool>("DataSharingConsent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("data_sharing_consent");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_notifications");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("language_code");

                    b.Property<string>("ProfileVisibility")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("profile_visibility");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("push_notifications");

                    b.Property<bool>("SmsNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("sms_notifications");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("timezone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_preferences");

                    b.ToTable("preferences");
                });
#pragma warning restore 612, 618
        }
    }
}
